// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDIcAoO1N1OF3QDPL6CKalKzSyoV9-i34',
    appId: '1:246322481984:web:7c8987cd8a3d961ac188a5',
    messagingSenderId: '246322481984',
    projectId: 'training-ea8b4',
    authDomain: 'training-ea8b4.firebaseapp.com',
    databaseURL: 'https://training-ea8b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'training-ea8b4.appspot.com',
    measurementId: 'G-TL28EHGL5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4zltHp9n67nr2xMhdDgIdAB9pI_1pPII',
    appId: '1:246322481984:android:46bb97521033f122c188a5',
    messagingSenderId: '246322481984',
    projectId: 'training-ea8b4',
    databaseURL: 'https://training-ea8b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'training-ea8b4.appspot.com',
  );
}
